export const CREATE_COURSE="CREATE_COURSE";
export const SET_API_DATA="SET_API_DATA";
export const LIST_COURSES="LIST_COURSES";
export const SET_PROMO_DATA="SET_PROMO_DATA";
export const SET_PROMO_ERROR="SET_PROMO_ERROR";
